# Generated by Django 4.2 on 2023-05-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_description_emp_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
