# Generated by Django 4.1.7 on 2023-05-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_emp_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='action',
            new_name='position',
        ),
    ]
