# Generated by Django 4.1.7 on 2023-05-10 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_action_emp_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='position',
            new_name='poste',
        ),
        migrations.AddField(
            model_name='emp',
            name='hireDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
