# Generated by Django 4.1.7 on 2023-05-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_emp_hiredate_remove_emp_phone_emp_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
