# Generated by Django 4.1.7 on 2023-05-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
